filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/gateway-server/gateway.log
    fields:
      source: gateway-server
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields:
      source: nginx-access

  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log
    fields:
      source: nginx-error

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:192.168.192.201:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  index: "gw-%{[fields.source]}-*"
  indices:
    - index: "gw-gateway-server-%{+yyyy.MM.dd}"
      when.equals:
        fields.source: "gateway-server"
    - index: "gw-nginx-access-%{+yyyy.MM.dd}"
      when.equals:
        fields.source: "nginx-access"
    - index: "gw-nginx-error-%{+yyyy.MM.dd}"
      when.equals:
        fields.source: "nginx-error"

setup.template.name: "gw-log"
setup.template.pattern: "gw-*"
setup.template.overwrite: true
setup.template.enabled: true
setup.ilm.enabled: false