version: '3'
services:
  auth-server:
    restart: always
    container_name: auth-server
    image: $IMAGE_REPO_URL/auth-server:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 6000:6000

  gateway-server:
    restart: always
    container_name: gateway-server
    image: $IMAGE_REPO_URL/gateway-server:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 7000:7000
    depends_on:
      - gateway-admin-server

  gateway-admin-server:
    restart: always
    container_name: gateway-admin-server
    image: $IMAGE_REPO_URL/gateway-admin-server:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 8000:8000

  admin-ui:
    restart: always
    container_name: admin-ui
    image: $IMAGE_REPO_URL/admin-ui:${IMAGE_VERSION}
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - gateway-server

  monitor-center:
    restart: always
    container_name: monitor-center
    image: $IMAGE_REPO_URL/monitor-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 9002:9002

  message-center:
    restart: always
    container_name: message-center
    image: $IMAGE_REPO_URL/message-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 9001:9001
#
#  tool-center:
#    restart: always
#    container_name: tool-center
#    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}
#    ports:
#      - 9003:9003