version: '3'
services:
  gateway-server:
    build:
      context: ./gateway/gateway-server
    image: $IMAGE_REPO_URL/gateway-server:${IMAGE_VERSION}

  gateway-admin-server:
    build:
      context: ./gateway/gateway-admin-server
    image: $IMAGE_REPO_URL/gateway-admin-server:${IMAGE_VERSION}

  gateway-admin-ui:
    build:
      context: ./gateway/gateway-admin-ui
    image: $IMAGE_REPO_URL/gateway-admin-ui:${IMAGE_VERSION}

  monitor:
    build:
      context: ./optional/monitor
    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}

  sentinel-dashboard:
    build:
      context: ./optional/sentinel-dashboard
    image: $IMAGE_REPO_URL/sentinel-dashboard:${IMAGE_VERSION}