version: '3'
services:
  auth-center:
    restart: always
    container_name: auth-center
    image: $IMAGE_REPO_URL/auth-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 7100:7100

  system-center:
    restart: always
    container_name: system-center
    image: $IMAGE_REPO_URL/system-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 7200:7200

  gateway-center:
    restart: always
    container_name: gateway-center
    image: $IMAGE_REPO_URL/gateway-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 7000:7000
    depends_on:
      - gateway-admin-center

  gateway-admin-center:
    restart: always
    container_name: gateway-admin-center
    image: $IMAGE_REPO_URL/gateway-admin-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 8000:8000

  admin-ui:
    restart: always
    container_name: admin-ui
    image: $IMAGE_REPO_URL/admin-ui:${IMAGE_VERSION}
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - gateway-center

  monitor-center:
    restart: always
    container_name: monitor-center
    image: $IMAGE_REPO_URL/monitor-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 9002:9002

  message-center:
    restart: always
    container_name: message-center
    image: $IMAGE_REPO_URL/message-center:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 9001:9001
#
#  tool-center:
#    restart: always
#    container_name: tool-center
#    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}
#    ports:
#      - 9003:9003