version: '3'
services:
  auth-center:
    build:
      context: ./auth-center
    image: $IMAGE_REPO_URL/auth-center:${IMAGE_VERSION}

  system-center:
    build:
      context: ./system-center
    image: $IMAGE_REPO_URL/system-center:${IMAGE_VERSION}

  gateway-center:
    build:
      context: ./gateway/gateway-center
    image: $IMAGE_REPO_URL/gateway-center:${IMAGE_VERSION}

  gateway-admin-center:
    build:
      context: ./gateway/gateway-admin-center
    image: $IMAGE_REPO_URL/gateway-admin-center:${IMAGE_VERSION}

  admin-ui:
    build:
      context: ./admin-ui
    image: $IMAGE_REPO_URL/admin-ui:${IMAGE_VERSION}

  monitor-center:
    build:
      context: ./optional/monitor-center
    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}

  message-center:
    build:
      context: ./optional/message-center
    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}
#
#  tool-center:
#    build:
#      context: ./optional/tool-center
#    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}