version: '3'
services:
  gateway-bootstrap:
    restart: always
    container_name: gateway-bootstrap
    image: dlhf/gateway-bootstrap:${image_version}
    ports:
      - 7000:7000

  gateway-admin-bootstrap:
    restart: always
    container_name: gateway-admin-bootstrap
    image: dlhf/gateway-admin-bootstrap:${image_version}
    ports:
      - 8000:8000

  gateway-admin-ui:
    restart: always
    container_name: gateway-admin-ui
    image: dlhf/gateway-admin-ui:${image_version}
    ports:
      - 80:80
    depends_on:
      - gateway-admin-bootstrap

  monitor:
    restart: always
    container_name: monitor
    image: dlhf/monitor:${image_version}
    ports:
      - 9000:9000