version: '3'
services:
  gateway-bootstrap:
    build:
      context: ./gateway/gateway-bootstrap
    restart: always
    container_name: gateway-bootstrap
    image: dlhf/gateway-bootstrap:${image_version}

  gateway-admin-bootstrap:
    build:
      context: ./gateway/gateway-admin-bootstrap
    restart: always
    container_name: gateway-admin-bootstrap
    image: dlhf/gateway-admin-bootstrap:${image_version}

  gateway-admin-ui:
    build:
      context: ./gateway/gateway-admin-ui/docker
    restart: always
    container_name: gateway-admin-ui
    image: dlhf/gateway-admin-ui:${image_version}

  monitor:
    build:
      context: ./optional/monitor
    restart: always
    container_name: monitor
    image: dlhf/monitor:${image_version}

  sentinel-dashboard:
    build:
      context: ./optional/sentinel-dashboard
    restart: always
    container_name: sentinel-dashboard
    image: dlhf/sentinel-dashboard:${image_version}