version: '3'
services:
  gateway-server:
    restart: always
    container_name: gateway-server
    image: $IMAGE_REPO_URL/gateway-server:${IMAGE_VERSION}
    volumes:
      - /app/logs:/app/logs
    ports:
      - 7000:7000
    depends_on:
      - gateway-admin-server
      - sentinel-dashboard

  gateway-admin-server:
    restart: always
    container_name: gateway-admin-server
    image: $IMAGE_REPO_URL/gateway-admin-server:${IMAGE_VERSION}
    ports:
      - 8000:8000

  gateway-admin-ui:
    restart: always
    container_name: gateway-admin-ui
    image: $IMAGE_REPO_URL/gateway-admin-ui:${IMAGE_VERSION}
    volumes:
      - /var/log/nginx:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - gateway-admin-server

  monitor:
    restart: always
    container_name: monitor
    image: $IMAGE_REPO_URL/monitor:${IMAGE_VERSION}
    ports:
      - 9000:9000

  sentinel-dashboard:
    restart: always
    container_name: sentinel-dashboard
    image: $IMAGE_REPO_URL/sentinel-dashboard:${IMAGE_VERSION}
    environment:
      SERVER_PORT: 9100
    ports:
      - 9100:9100